---

- name: Set Timezone (wily and below)
  become: yes
  copy:
    content: "{{ sansible_ntp_timezone }}\n"
    dest: /etc/timezone
  when: ansible_distribution_version is version('15.10', '<=')
  notify:
    - update timezone

- name: Set Timezone (xenial and above)
  become: yes
  file:
    path: /etc/localtime
    src: "/usr/share/zoneinfo/{{ sansible_ntp_timezone }}"
    state: link
  when: ansible_distribution_version is version('16.04', '>=')
  notify:
    - update timezone

- name: Setup NTP
  become: yes
  template:
    dest: /etc/ntp.conf
    src: ntp.conf.j2
  notify:
    - restart ntp
