---

- name: Install NTP, tzdata
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ntp
    - tzdata

- name: Ensure NTP is running and enabled
  become: yes
  service:
    name: ntp
    state: started
    enabled: yes
