---

driver:
  name: docker

platforms:
  - name: sansible_ntp-trusty
    image: ubuntu:trusty
  - name: sansible_ntp-xenial
    image: solita/ubuntu-systemd:xenial
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: sansible_ntp-bionic
    image: solita/ubuntu-systemd:bionic
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  lint:
    name: ansible-lint

lint:
  name: yamllint
  options:
    config-data:
      extends: default
      ignore: .venv_ansible*
      rules:
        line-length:
          max: 300
        truthy: disable

dependency:
  name: galaxy

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
